# Generated by Django 4.1.3 on 2022-11-09 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_alter_pacient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacient',
            old_name='id',
            new_name='pacient_id',
        ),
    ]
