# Generated by Django 4.1.3 on 2022-11-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_rename_id_pacient_pacient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='gender',
            field=models.CharField(choices=[(1, 'Мужчина'), (2, 'Женщина')], max_length=20),
        ),
    ]
