# Generated by Django 4.1.3 on 2022-11-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_alter_pacient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='gender',
            field=models.CharField(choices=[('м', 'Мужчина'), ('ж', 'Женщина')], max_length=20),
        ),
    ]
