# Generated by Django 4.1.3 on 2022-11-17 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_alter_pacient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepocedureCard',
            fields=[
                ('pacient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='medical.pacient')),
                ('admission_date', models.DateTimeField()),
                ('sing_date', models.DateField()),
                ('is_smoker', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Да')], default=' ', max_length=3)),
                ('packyears', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='pacient',
            name='gender',
            field=models.CharField(choices=[('м', 'Мужчина'), ('ж', 'Женщина')], default=' ', max_length=20),
        ),
    ]
