# Generated by Django 4.1.3 on 2022-11-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_prepocedurecard_alter_pacient_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prepocedurecard',
            old_name='sing_date',
            new_name='sign_date',
        ),
        migrations.AlterField(
            model_name='prepocedurecard',
            name='is_smoker',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default=' ', max_length=3),
        ),
    ]
