# Generated by Django 4.1.3 on 2022-11-17 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_rename_sing_date_prepocedurecard_sign_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreprocedureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField()),
                ('sign_date', models.DateField()),
                ('is_smoker', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default=' ', max_length=3)),
                ('packyears', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('pacient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.pacient')),
            ],
        ),
        migrations.DeleteModel(
            name='PrepocedureCard',
        ),
    ]
