# Generated by Django 4.1.3 on 2022-11-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_remove_preprocedurecard_id_preprocedurecard_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprocedurecard',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='card_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
