# Generated by Django 4.1.3 on 2022-11-19 17:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0014_alter_preprocedurecard_admission_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preprocedurecard',
            old_name='card_id',
            new_name='preprocedure_card_id',
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='admission_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 17, 58, 22, 82310, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 17, 58, 22, 82310, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='sign_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 19, 17, 58, 22, 82310, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('history_card_id', models.AutoField(primary_key=True, serialize=False)),
                ('relevant_disease', models.BooleanField(default=False)),
                ('has_diabetes', models.BooleanField(default=False)),
                ('has_hypertension', models.BooleanField(default=False)),
                ('has_cardiovascular', models.BooleanField(default=False)),
                ('has_cord', models.BooleanField(default=False)),
                ('has_renal_disease', models.BooleanField(default=False)),
                ('has_liver_disease', models.BooleanField(default=False)),
                ('has_sleep_aphea', models.BooleanField(default=False)),
                ('has_gerd', models.BooleanField(default=False)),
                ('has_depression', models.BooleanField(default=False)),
                ('has_osteoarthritis', models.BooleanField(default=False)),
                ('has_chronic_pain', models.BooleanField(default=False)),
                ('has_stroke', models.BooleanField(default=False)),
                ('pacient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.pacient')),
            ],
        ),
    ]
