# Generated by Django 4.1.3 on 2022-11-19 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0015_rename_card_id_preprocedurecard_preprocedure_card_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='relevant_disease',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=3),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='admission_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 18, 36, 4, 370299, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 18, 36, 4, 370299, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='sign_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 19, 18, 36, 4, 370299, tzinfo=datetime.timezone.utc)),
        ),
    ]
