# Generated by Django 4.1.3 on 2022-11-20 11:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0016_alter_medicalhistory_relevant_disease_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='pacient_id',
            new_name='card_id',
        ),
        migrations.RemoveField(
            model_name='preprocedurecard',
            name='pacient_id',
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='history_card_id',
            field=models.AutoField(default=-1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='admission_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 11, 13, 12, 713494, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 11, 13, 12, 713494, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='preprocedure_card_id',
            field=models.AutoField(default=-1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='sign_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 20, 11, 13, 12, 713494, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('pacient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.pacient')),
            ],
        ),
        migrations.AddField(
            model_name='preprocedurecard',
            name='card_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='medical.card'),
        ),
    ]
