# Generated by Django 4.1.3 on 2022-11-20 19:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0023_alter_preprocedurecard_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='card_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='medical.card'),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='admission_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 19, 36, 43, 371714, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 19, 36, 43, 371714, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='sign_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 20, 19, 36, 43, 371714, tzinfo=datetime.timezone.utc)),
        ),
    ]
