# Generated by Django 4.1.3 on 2022-11-20 20:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0024_alter_medicalhistory_card_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprocedurecard',
            name='admission_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 20, 57, 7, 656231, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 20, 57, 7, 656231, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='sign_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 20, 20, 57, 7, 656231, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='SurgicalHistory',
            fields=[
                ('surgical_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('has_abdominal_surgery', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=3)),
                ('surgion_description', models.TextField(default='')),
                ('card_id', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='medical.card')),
            ],
        ),
    ]
