# Generated by Django 4.1.3 on 2022-11-21 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0026_alter_preprocedurecard_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastrointestinalprocedure',
            name='bariatric',
            field=models.CharField(blank=True, default=' ', max_length=80),
        ),
        migrations.AlterField(
            model_name='gastrointestinalprocedure',
            name='cholecystectomy',
            field=models.CharField(blank=True, default=' ', max_length=80),
        ),
        migrations.AlterField(
            model_name='gastrointestinalprocedure',
            name='esophageal',
            field=models.CharField(blank=True, default=' ', max_length=80),
        ),
        migrations.AlterField(
            model_name='gastrointestinalprocedure',
            name='esophagus_implants',
            field=models.CharField(blank=True, default=' ', max_length=80),
        ),
        migrations.AlterField(
            model_name='gastrointestinalprocedure',
            name='first_surgeon',
            field=models.CharField(blank=True, default=' ', max_length=40),
        ),
        migrations.AlterField(
            model_name='gastrointestinalprocedure',
            name='fundoplication',
            field=models.CharField(blank=True, default=' ', max_length=80),
        ),
        migrations.AlterField(
            model_name='gastrointestinalprocedure',
            name='gastric',
            field=models.CharField(blank=True, default=' ', max_length=80),
        ),
        migrations.AlterField(
            model_name='gastrointestinalprocedure',
            name='hemicolectomy',
            field=models.CharField(blank=True, default=' ', max_length=80),
        ),
        migrations.AlterField(
            model_name='gastrointestinalprocedure',
            name='hernia_bilateral',
            field=models.CharField(blank=True, default=' ', max_length=80),
        ),
        migrations.AlterField(
            model_name='gastrointestinalprocedure',
            name='hernia_unilateral',
            field=models.CharField(blank=True, default=' ', max_length=80),
        ),
        migrations.AlterField(
            model_name='gastrointestinalprocedure',
            name='linx_implants',
            field=models.CharField(blank=True, default=' ', max_length=80),
        ),
        migrations.AlterField(
            model_name='gastrointestinalprocedure',
            name='liver_surgery',
            field=models.CharField(blank=True, default=' ', max_length=80),
        ),
        migrations.AlterField(
            model_name='gastrointestinalprocedure',
            name='other',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='gastrointestinalprocedure',
            name='rectal',
            field=models.CharField(blank=True, default=' ', max_length=80),
        ),
        migrations.AlterField(
            model_name='gastrointestinalprocedure',
            name='second_surgeon',
            field=models.CharField(blank=True, default=' ', max_length=40),
        ),
        migrations.AlterField(
            model_name='gastrointestinalprocedure',
            name='sigmoid_resection',
            field=models.CharField(blank=True, default=' ', max_length=80),
        ),
        migrations.AlterField(
            model_name='gastrointestinalprocedure',
            name='ventral_hernia',
            field=models.CharField(blank=True, default=' ', max_length=80),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='admission_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 7, 51, 11, 620412, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 7, 51, 11, 620412, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='sign_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 21, 7, 51, 11, 620412, tzinfo=datetime.timezone.utc)),
        ),
    ]
