# Generated by Django 4.1.3 on 2022-11-21 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0028_alter_preprocedurecard_admission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastrointestinalprocedure',
            name='indication_for_procedure',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AddField(
            model_name='gastrointestinalprocedure',
            name='procedural_details',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AddField(
            model_name='gastrointestinalprocedure',
            name='special_conditions_present',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AddField(
            model_name='gastrointestinalprocedure',
            name='specification',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='admission_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 8, 18, 59, 225542, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 8, 18, 59, 225542, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='sign_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 21, 8, 18, 59, 225542, tzinfo=datetime.timezone.utc)),
        ),
    ]
