# Generated by Django 4.1.3 on 2022-11-21 09:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0029_gastrointestinalprocedure_indication_for_procedure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprocedurecard',
            name='admission_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 9, 25, 13, 951807, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 9, 25, 13, 951807, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='sign_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 21, 9, 25, 13, 951807, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='UrologicalProcedure',
            fields=[
                ('uro_procedure_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_surgeon', models.CharField(blank=True, default=' ', max_length=40)),
                ('second_surgeon', models.CharField(blank=True, default=' ', max_length=40)),
                ('radical_prostatectomy', models.CharField(blank=True, default=' ', max_length=200)),
                ('lymph_dissection', models.CharField(blank=True, default=' ', max_length=200)),
                ('adrenalectomy', models.CharField(blank=True, default=' ', max_length=200)),
                ('simple_prostatectomy', models.CharField(blank=True, default=' ', max_length=200)),
                ('partial_nephrectomy', models.CharField(blank=True, default=' ', max_length=200)),
                ('radical_nephrectomy', models.CharField(blank=True, default=' ', max_length=200)),
                ('radical_cystectomy', models.CharField(blank=True, default=' ', max_length=200)),
                ('ureter_reimplant', models.CharField(blank=True, default=' ', max_length=200)),
                ('pyeloplasty_UPJ', models.CharField(blank=True, default=' ', max_length=200)),
                ('other', models.CharField(blank=True, default=' ', max_length=200)),
                ('indication_for_procedure', models.TextField(blank=True, default=' ')),
                ('procedural_details', models.TextField(blank=True, default=' ')),
                ('specification', models.TextField(blank=True, default=' ')),
                ('special_conditions_present', models.TextField(blank=True, default=' ')),
                ('card_id', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='medical.card')),
            ],
        ),
    ]
