# Generated by Django 4.1.3 on 2022-11-21 10:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0030_alter_preprocedurecard_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprocedurecard',
            name='admission_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 10, 59, 11, 179162, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 10, 59, 11, 179162, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='sign_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 21, 10, 59, 11, 179162, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='SurgicalProceduralDetail',
            fields=[
                ('surg_proc_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('surg_start_time', models.TimeField(default=datetime.datetime(2022, 11, 21, 10, 59, 11, 181190, tzinfo=datetime.timezone.utc))),
                ('docking_begins', models.TimeField(default=datetime.datetime(2022, 11, 21, 10, 59, 11, 181190, tzinfo=datetime.timezone.utc))),
                ('docking_ends', models.TimeField(default=datetime.datetime(2022, 11, 21, 10, 59, 11, 181190, tzinfo=datetime.timezone.utc))),
                ('console_start_time', models.TimeField(default=datetime.datetime(2022, 11, 21, 10, 59, 11, 181190, tzinfo=datetime.timezone.utc))),
                ('console_end_time', models.TimeField(default=datetime.datetime(2022, 11, 21, 10, 59, 11, 181190, tzinfo=datetime.timezone.utc))),
                ('surg_end_time', models.TimeField(default=datetime.datetime(2022, 11, 21, 10, 59, 11, 181190, tzinfo=datetime.timezone.utc))),
                ('table_height', models.IntegerField(default=0)),
                ('supine_position', models.CharField(blank=True, default=' ', max_length=80)),
                ('lithotomy_position', models.CharField(blank=True, default=' ', max_length=80)),
                ('lateral_position', models.CharField(blank=True, default=' ', max_length=80)),
                ('prone_position', models.CharField(blank=True, default=' ', max_length=80)),
                ('beach_chair_position', models.CharField(blank=True, default=' ', max_length=80)),
                ('other', models.CharField(blank=True, default=' ', max_length=200)),
                ('card_id', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='medical.card')),
            ],
        ),
    ]
