# Generated by Django 4.1.3 on 2022-11-21 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0031_alter_preprocedurecard_admission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgicalproceduraldetail',
            name='indication_for_procedure',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AddField(
            model_name='surgicalproceduraldetail',
            name='procedural_details',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AddField(
            model_name='surgicalproceduraldetail',
            name='special_conditions_present',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AddField(
            model_name='surgicalproceduraldetail',
            name='specification',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='admission_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 11, 48, 25, 963955, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 11, 48, 25, 963955, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='sign_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 21, 11, 48, 25, 963955, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='console_end_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 21, 11, 48, 25, 965974, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='console_start_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 21, 11, 48, 25, 965974, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='docking_begins',
            field=models.TimeField(default=datetime.datetime(2022, 11, 21, 11, 48, 25, 965974, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='docking_ends',
            field=models.TimeField(default=datetime.datetime(2022, 11, 21, 11, 48, 25, 965974, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='surg_end_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 21, 11, 48, 25, 965974, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='surg_start_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 21, 11, 48, 25, 965974, tzinfo=datetime.timezone.utc)),
        ),
    ]
