# Generated by Django 4.1.3 on 2022-11-21 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0033_alter_preprocedurecard_admission_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surgicalproceduraldetail',
            name='beach_chair_position',
        ),
        migrations.RemoveField(
            model_name='surgicalproceduraldetail',
            name='lateral_position',
        ),
        migrations.RemoveField(
            model_name='surgicalproceduraldetail',
            name='lithotomy_position',
        ),
        migrations.RemoveField(
            model_name='surgicalproceduraldetail',
            name='other',
        ),
        migrations.RemoveField(
            model_name='surgicalproceduraldetail',
            name='prone_position',
        ),
        migrations.RemoveField(
            model_name='surgicalproceduraldetail',
            name='supine_position',
        ),
        migrations.AddField(
            model_name='surgicalproceduraldetail',
            name='position',
            field=models.CharField(blank=True, choices=[('Положение лежа на спине', 'Положение лежа на спине'), ('Положения лежа на животе', 'Положения лежа на животе'), ('Боковое положение', 'Боковое положение'), ('Положение с согнутыми ногами', 'Положение с согнутыми ногами'), ('Положение шезлонга', 'Положение шезлонга')], default=' ', max_length=80),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='admission_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 12, 27, 32, 28113, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 12, 27, 32, 28113, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='sign_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 21, 12, 27, 32, 28113, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='console_end_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 21, 12, 27, 32, 30108, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='console_start_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 21, 12, 27, 32, 30108, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='docking_begins',
            field=models.TimeField(default=datetime.datetime(2022, 11, 21, 12, 27, 32, 30108, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='docking_ends',
            field=models.TimeField(default=datetime.datetime(2022, 11, 21, 12, 27, 32, 30108, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='surg_end_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 21, 12, 27, 32, 30108, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='surg_start_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 21, 12, 27, 32, 30108, tzinfo=datetime.timezone.utc)),
        ),
    ]
