# Generated by Django 4.1.3 on 2022-11-23 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0038_alter_preprocedurecard_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprocedurecard',
            name='admission_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 7, 21, 46, 962443, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 7, 21, 46, 962443, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='sign_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 23, 7, 21, 46, 962443, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='console_end_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 23, 7, 21, 46, 962443, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='console_start_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 23, 7, 21, 46, 962443, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='docking_begins',
            field=models.TimeField(default=datetime.datetime(2022, 11, 23, 7, 21, 46, 962443, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='docking_ends',
            field=models.TimeField(default=datetime.datetime(2022, 11, 23, 7, 21, 46, 962443, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='surg_end_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 23, 7, 21, 46, 962443, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='surg_start_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 23, 7, 21, 46, 962443, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='trocardlocation',
            name='table11',
            field=models.CharField(default='1A', max_length=2),
        ),
        migrations.AlterField(
            model_name='trocardlocation',
            name='table12',
            field=models.CharField(default='1A', max_length=2),
        ),
        migrations.AlterField(
            model_name='trocardlocation',
            name='table13',
            field=models.CharField(default='1A', max_length=2),
        ),
        migrations.AlterField(
            model_name='trocardlocation',
            name='table14',
            field=models.CharField(default='1A', max_length=2),
        ),
        migrations.AlterField(
            model_name='trocardlocation',
            name='table21',
            field=models.CharField(default='1A', max_length=2),
        ),
        migrations.AlterField(
            model_name='trocardlocation',
            name='table22',
            field=models.CharField(default='1A', max_length=2),
        ),
        migrations.AlterField(
            model_name='trocardlocation',
            name='table23',
            field=models.CharField(default='1A', max_length=2),
        ),
        migrations.AlterField(
            model_name='trocardlocation',
            name='table24',
            field=models.CharField(default='1A', max_length=2),
        ),
        migrations.AlterField(
            model_name='trocardlocation',
            name='table31',
            field=models.CharField(default='1A', max_length=2),
        ),
        migrations.AlterField(
            model_name='trocardlocation',
            name='table32',
            field=models.CharField(default='1A', max_length=2),
        ),
        migrations.AlterField(
            model_name='trocardlocation',
            name='table33',
            field=models.CharField(default='1A', max_length=2),
        ),
        migrations.AlterField(
            model_name='trocardlocation',
            name='table34',
            field=models.CharField(default='1A', max_length=2),
        ),
        migrations.AlterField(
            model_name='trocardlocation',
            name='table41',
            field=models.CharField(default='1A', max_length=2),
        ),
        migrations.AlterField(
            model_name='trocardlocation',
            name='table42',
            field=models.CharField(default='1A', max_length=2),
        ),
        migrations.AlterField(
            model_name='trocardlocation',
            name='table43',
            field=models.CharField(default='1A', max_length=2),
        ),
        migrations.AlterField(
            model_name='trocardlocation',
            name='table44',
            field=models.CharField(default='1A', max_length=2),
        ),
    ]
