# Generated by Django 4.1.3 on 2022-11-23 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0048_alter_preprocedurecard_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentused',
            name='table_ai1',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_ai2',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_ai3',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_ai4',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_bi1_3',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_bi1_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_bi2_3',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_bi2_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_bi3_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_bi4_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_bi5_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_ca1',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_mi1_3',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_mi1_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_mi2_3',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_mi2_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_mi3_3',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_mi3_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_mi4_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_mi5_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_mi6_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_mi7_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_mi8_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_pi10_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_pi11_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_pi12_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_pi13_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_pi14_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_pi15_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_pi16_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_pi17_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_pi1_10',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_pi1_3',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_pi1_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_pi2_10',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_pi2_3',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_pi2_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_pi3_3',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_pi3_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_pi4_3',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_pi4_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_pi5_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_pi6_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_pi7_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_pi8_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_pi9_5',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_rad1',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_rad2',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_rad3',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='table_us',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='admission_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 19, 46, 40, 853142, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 19, 46, 40, 853142, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='sign_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 23, 19, 46, 40, 853142, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='console_end_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 23, 19, 46, 40, 855135, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='console_start_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 23, 19, 46, 40, 855135, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='docking_begins',
            field=models.TimeField(default=datetime.datetime(2022, 11, 23, 19, 46, 40, 855135, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='docking_ends',
            field=models.TimeField(default=datetime.datetime(2022, 11, 23, 19, 46, 40, 855135, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='surg_end_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 23, 19, 46, 40, 855135, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='surg_start_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 23, 19, 46, 40, 855135, tzinfo=datetime.timezone.utc)),
        ),
    ]
