# Generated by Django 4.1.3 on 2022-11-24 08:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0051_instrumentused_table_ca2_instrumentused_table_ca3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprocedurecard',
            name='admission_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 8, 59, 39, 929168, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 8, 59, 39, 929168, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='sign_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 24, 8, 59, 39, 929168, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='console_end_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 24, 8, 59, 39, 933137, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='console_start_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 24, 8, 59, 39, 933137, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='docking_begins',
            field=models.TimeField(default=datetime.datetime(2022, 11, 24, 8, 59, 39, 933137, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='docking_ends',
            field=models.TimeField(default=datetime.datetime(2022, 11, 24, 8, 59, 39, 933137, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='surg_end_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 24, 8, 59, 39, 933137, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='surg_start_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 24, 8, 59, 39, 933137, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='AncillaryInstruments',
            fields=[
                ('ai_id', models.AutoField(primary_key=True, serialize=False)),
                ('tacker', models.BooleanField(blank=True, default=False)),
                ('clips', models.BooleanField(blank=True, default=False)),
                ('staplers_l', models.BooleanField(blank=True, default=False)),
                ('staplers_c', models.BooleanField(blank=True, default=False)),
                ('other', models.BooleanField(blank=True, default=False)),
                ('comment', models.TextField(blank=True, default=' ')),
                ('monopolar', models.BooleanField(blank=True, default=False)),
                ('bipolar', models.BooleanField(blank=True, default=False)),
                ('ultrasound', models.BooleanField(blank=True, default=False)),
                ('high_energy_device', models.BooleanField(blank=True, default=False)),
                ('card_id', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='medical.card')),
            ],
        ),
    ]
