# Generated by Django 4.1.3 on 2022-11-24 12:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0052_alter_preprocedurecard_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preprocedurecard',
            name='admission_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 12, 56, 4, 499947, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 12, 56, 4, 499947, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='sign_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 24, 12, 56, 4, 499947, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='console_end_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 24, 12, 56, 4, 503915, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='console_start_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 24, 12, 56, 4, 503915, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='docking_begins',
            field=models.TimeField(default=datetime.datetime(2022, 11, 24, 12, 56, 4, 503915, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='docking_ends',
            field=models.TimeField(default=datetime.datetime(2022, 11, 24, 12, 56, 4, 503915, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='surg_end_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 24, 12, 56, 4, 503915, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='surg_start_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 24, 12, 56, 4, 503915, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='PostProcedural',
            fields=[
                ('postproc_id', models.AutoField(primary_key=True, serialize=False)),
                ('brought_ICU', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=3)),
                ('start_ICU', models.DateTimeField(blank=True)),
                ('end_ICU', models.DateTimeField(blank=True)),
                ('generic_name_l1', models.CharField(blank=True, max_length=100)),
                ('dose_l1', models.IntegerField(blank=True)),
                ('unit_l1', models.CharField(blank=True, max_length=10)),
                ('generic_name_l2', models.CharField(blank=True, max_length=100)),
                ('dose_l2', models.IntegerField(blank=True)),
                ('unit_l2', models.CharField(blank=True, max_length=10)),
                ('generic_name_l3', models.CharField(blank=True, max_length=100)),
                ('dose_l3', models.IntegerField(blank=True)),
                ('unit_l3', models.CharField(blank=True, max_length=10)),
                ('datetime_discharge', models.DateTimeField(blank=True)),
                ('adverse_event_noted', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=3)),
                ('card_id', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='medical.card')),
            ],
        ),
    ]
