# Generated by Django 4.1.3 on 2022-11-25 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0057_alter_postprocedural_datetime_discharge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodloss',
            name='end_by_robot',
            field=models.CharField(choices=[('YES', 'YES'), ('YES', 'YES')], default='Нет', max_length=3),
        ),
        migrations.AlterField(
            model_name='bloodloss',
            name='temporary_conversion',
            field=models.CharField(choices=[('YES', 'YES'), ('YES', 'YES')], default='Нет', max_length=3),
        ),
        migrations.AlterField(
            model_name='bloodloss',
            name='undergo_conversion_lap',
            field=models.CharField(choices=[('YES', 'YES'), ('YES', 'YES')], default='Нет', max_length=3),
        ),
        migrations.AlterField(
            model_name='bloodloss',
            name='undergo_conversion_open',
            field=models.CharField(choices=[('YES', 'YES'), ('YES', 'YES')], default='Нет', max_length=3),
        ),
        migrations.AlterField(
            model_name='followup',
            name='any_AE',
            field=models.CharField(choices=[('YES', 'YES'), ('YES', 'YES')], default='Нет', max_length=3),
        ),
        migrations.AlterField(
            model_name='followup',
            name='date_followup',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 25, 9, 26, 10, 434373, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='relevant_disease',
            field=models.CharField(choices=[('YES', 'YES'), ('YES', 'YES')], default='Нет', max_length=3),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='postprocedural',
            name='adverse_event_noted',
            field=models.CharField(choices=[('YES', 'YES'), ('YES', 'YES')], default='Нет', max_length=3),
        ),
        migrations.AlterField(
            model_name='postprocedural',
            name='brought_ICU',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('YES', 'YES')], default='Нет', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='postprocedural',
            name='datetime_discharge',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 25, 9, 26, 10, 434373, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='postprocedural',
            name='end_ICU',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 25, 9, 26, 10, 434373, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='postprocedural',
            name='start_ICU',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 25, 9, 26, 10, 434373, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='admission_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 25, 9, 26, 10, 424399, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 25, 9, 26, 10, 424399, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='is_smoker',
            field=models.CharField(choices=[('YES', 'YES'), ('YES', 'YES')], default='Нет', max_length=3),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='sign_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 25, 9, 26, 10, 424399, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalhistory',
            name='has_abdominal_surgery',
            field=models.CharField(choices=[('YES', 'YES'), ('YES', 'YES')], default='Нет', max_length=3),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='console_end_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 25, 9, 26, 10, 426393, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='console_start_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 25, 9, 26, 10, 426393, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='docking_begins',
            field=models.TimeField(default=datetime.datetime(2022, 11, 25, 9, 26, 10, 426393, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='docking_ends',
            field=models.TimeField(default=datetime.datetime(2022, 11, 25, 9, 26, 10, 426393, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='surg_end_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 25, 9, 26, 10, 426393, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='surg_start_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 25, 9, 26, 10, 426393, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='trocardlocation',
            name='local_anesthesy_used',
            field=models.CharField(choices=[('YES', 'YES'), ('YES', 'YES')], default='Нет', max_length=3),
        ),
    ]
