# Generated by Django 4.1.3 on 2022-11-26 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0061_alter_followup_date_followup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='date_followup',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 26, 10, 4, 22, 569258, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='postprocedural',
            name='datetime_discharge',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 26, 10, 4, 22, 568265, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='postprocedural',
            name='end_ICU',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 26, 10, 4, 22, 568265, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='postprocedural',
            name='start_ICU',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 26, 10, 4, 22, 568265, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='admission_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 10, 4, 22, 562264, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 10, 4, 22, 562264, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='sign_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 26, 10, 4, 22, 562264, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='console_end_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 26, 10, 4, 22, 564275, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='console_start_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 26, 10, 4, 22, 564275, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='docking_begins',
            field=models.TimeField(default=datetime.datetime(2022, 11, 26, 10, 4, 22, 564275, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='docking_ends',
            field=models.TimeField(default=datetime.datetime(2022, 11, 26, 10, 4, 22, 564275, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='surg_end_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 26, 10, 4, 22, 564275, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='surg_start_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 26, 10, 4, 22, 564275, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='urologicalprocedure',
            name='adrenalectomy',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='urologicalprocedure',
            name='lymph_dissection',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='urologicalprocedure',
            name='partial_nephrectomy',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='urologicalprocedure',
            name='pyeloplasty_UPJ',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='urologicalprocedure',
            name='radical_cystectomy',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='urologicalprocedure',
            name='radical_nephrectomy',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='urologicalprocedure',
            name='radical_prostatectomy',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='urologicalprocedure',
            name='simple_prostatectomy',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='urologicalprocedure',
            name='ureter_reimplant',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
