# Generated by Django 4.1.3 on 2022-11-26 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0065_alter_followup_date_followup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='date_followup',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 26, 11, 31, 20, 403914, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='postprocedural',
            name='datetime_discharge',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 26, 11, 31, 20, 403914, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='postprocedural',
            name='end_ICU',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 26, 11, 31, 20, 403914, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='postprocedural',
            name='start_ICU',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 26, 11, 31, 20, 403914, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='admission_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 11, 31, 20, 398929, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 11, 31, 20, 398929, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='sign_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 26, 11, 31, 20, 398929, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='console_end_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 26, 11, 31, 20, 400921, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='console_start_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 26, 11, 31, 20, 400921, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='docking_begins',
            field=models.TimeField(default=datetime.datetime(2022, 11, 26, 11, 31, 20, 400921, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='docking_ends',
            field=models.TimeField(default=datetime.datetime(2022, 11, 26, 11, 31, 20, 400921, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='surg_end_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 26, 11, 31, 20, 400921, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='surg_start_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 26, 11, 31, 20, 399924, tzinfo=datetime.timezone.utc)),
        ),
    ]
