# Generated by Django 4.1.3 on 2022-11-26 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0066_alter_followup_date_followup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='date_followup',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 26, 11, 33, 1, 677167, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='diameter',
            field=models.CharField(choices=[('5mm', '5mm'), ('10mm', '10mm')], default=' ', max_length=4),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='dimension',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('4D', '4D')], default=' ', max_length=2),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='manufacturer',
            field=models.CharField(choices=[('Conmed', 'Conmed'), ('NovaDAQ', 'NovaDAQ'), ('Wolf', 'Wolf'), ('Stryker', 'Stryker'), ('Storz', 'Storz'), ('Olympus', 'Olympus')], default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='instrumentused',
            name='optic_degree',
            field=models.CharField(choices=[('0°', '0°'), ('30°', '30°')], default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='postprocedural',
            name='datetime_discharge',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 26, 11, 33, 1, 677167, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='postprocedural',
            name='end_ICU',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 26, 11, 33, 1, 677167, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='postprocedural',
            name='start_ICU',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 26, 11, 33, 1, 677167, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='admission_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 11, 33, 1, 672180, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 11, 33, 1, 672180, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='preprocedurecard',
            name='sign_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 26, 11, 33, 1, 672180, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='console_end_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 26, 11, 33, 1, 674174, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='console_start_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 26, 11, 33, 1, 674174, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='docking_begins',
            field=models.TimeField(default=datetime.datetime(2022, 11, 26, 11, 33, 1, 674174, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='docking_ends',
            field=models.TimeField(default=datetime.datetime(2022, 11, 26, 11, 33, 1, 674174, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='surg_end_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 26, 11, 33, 1, 674174, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='surgicalproceduraldetail',
            name='surg_start_time',
            field=models.TimeField(default=datetime.datetime(2022, 11, 26, 11, 33, 1, 674174, tzinfo=datetime.timezone.utc)),
        ),
    ]
